# Compare Focal Species CSV vs XLSX

This notebook compares the current workspace files:

- `Focal_Species_Cohort_Medication_Table.csv`
- `Focal_Species_Cohort_Medication_Table_TSG.xlsx`

The comparison is **exact** on these three columns:

- `Cohort`
- `Species`
- `Corresponding Medication`

The Excel file is read by skipping its first title row so that the true header row is used.

In [1]:
from pathlib import Path

import pandas as pd
from openpyxl import load_workbook
from IPython.display import display

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 200)

csv_path = Path("Focal_Species_Cohort_Medication_Table.csv")
xlsx_path = Path("Focal_Species_Cohort_Medication_Table_TSG.xlsx")

csv_df = pd.read_csv(csv_path, dtype=str).fillna("")

wb = load_workbook(xlsx_path, data_only=True)
ws = wb[wb.sheetnames[0]]
rows = list(ws.iter_rows(values_only=True))
xlsx_df = pd.DataFrame(rows[2:], columns=rows[1]).dropna(how="all").fillna("")

target_cols = ["Cohort", "Species", "Corresponding Medication"]
csv_df = csv_df[target_cols].copy()
xlsx_df = xlsx_df[target_cols].copy()

for df in (csv_df, xlsx_df):
    for col in target_cols:
        df[col] = df[col].astype(str).str.strip()

csv_df = csv_df.drop_duplicates().sort_values(target_cols).reset_index(drop=True)
xlsx_df = xlsx_df.drop_duplicates().sort_values(target_cols).reset_index(drop=True)

print(f"CSV rows   : {len(csv_df)}")
print(f"XLSX rows  : {len(xlsx_df)}")
print(f"Workbook   : {xlsx_path.name}")
print(f"CSV file   : {csv_path.name}")

CSV rows   : 170
XLSX rows  : 106
Workbook   : Focal_Species_Cohort_Medication_Table_TSG.xlsx
CSV file   : Focal_Species_Cohort_Medication_Table.csv

In [2]:
common_rows = (
    xlsx_df.merge(csv_df, on=target_cols, how="inner")
    .drop_duplicates()
    .sort_values(target_cols)
    .reset_index(drop=True)
)

xlsx_only_rows = (
    xlsx_df.merge(csv_df, on=target_cols, how="left", indicator=True)
    .query("_merge == 'left_only'")
    [target_cols]
    .sort_values(target_cols)
    .reset_index(drop=True)
)

csv_only_rows = (
    csv_df.merge(xlsx_df, on=target_cols, how="left", indicator=True)
    .query("_merge == 'left_only'")
    [target_cols]
    .sort_values(target_cols)
    .reset_index(drop=True)
)

print(f"Common exact rows        : {len(common_rows)}")
print(f"Rows only in XLSX        : {len(xlsx_only_rows)}")
print(f"Rows only in CSV         : {len(csv_only_rows)}")

Common exact rows        : 69
Rows only in XLSX        : 37
Rows only in CSV         : 101

## Common Exact Rows

In [3]:
display(common_rows)
common_rows

        Cohort                          Species Corresponding Medication
0   MetaCardis              Rothia_mucilaginosa             Esomeprazole
1   MetaCardis              Rothia_mucilaginosa             Lansoprazole
2   MetaCardis              Rothia_mucilaginosa               Omeprazole
3   MetaCardis              Rothia_mucilaginosa              Rabeprazole
4   MetaCardis          Streptococcus_australis               Olmesartan
5   MetaCardis          Streptococcus_cristatus             Rosuvastatin
6   MetaCardis             Streptococcus_downei               Torasemide
7   MetaCardis            Streptococcus_equinus              Clopidogrel
8   MetaCardis            Streptococcus_equinus                Diltiazem
9   MetaCardis            Streptococcus_equinus              Rabeprazole
10  MetaCardis       Streptococcus_gallolyticus              Allopurinol
11  MetaCardis       Streptococcus_gallolyticus                Metformin
12  MetaCardis           Streptococcus_gordonii                 Apixaban
13  MetaCardis           Streptococcus_gordonii             Esomeprazole
14  MetaCardis           Streptococcus_gordonii               Furosemide
15  MetaCardis           Streptococcus_gordonii             Lansoprazole
16  MetaCardis           Streptococcus_gordonii             Vildagliptin
17  MetaCardis           Streptococcus_infantis             Esomeprazole
18  MetaCardis           Streptococcus_infantis               Olmesartan
19  MetaCardis        Streptococcus_macedonicus            Dapagliflozin
20  MetaCardis            Streptococcus_milleri                Metformin
21  MetaCardis            Streptococcus_milleri              Rabeprazole
22  MetaCardis              Streptococcus_mitis             Esomeprazole
23  MetaCardis              Streptococcus_mitis               Furosemide
24  MetaCardis              Streptococcus_mitis               Olmesartan
25  MetaCardis             Streptococcus_oralis              Clopidogrel
26  MetaCardis             Streptococcus_oralis             Esomeprazole
27  MetaCardis             Streptococcus_oralis               Furosemide
28  MetaCardis             Streptococcus_oralis                Metformin
29  MetaCardis             Streptococcus_oralis               Olmesartan
30  MetaCardis             Streptococcus_oralis              Rabeprazole
31  MetaCardis      Streptococcus_parasanguinis              Clopidogrel
32  MetaCardis      Streptococcus_parasanguinis             Esomeprazole
33  MetaCardis      Streptococcus_parasanguinis             Lansoprazole
34  MetaCardis      Streptococcus_parasanguinis                Metformin
35  MetaCardis      Streptococcus_parasanguinis               Omeprazole
36  MetaCardis         Streptococcus_salivarius             Esomeprazole
37  MetaCardis         Streptococcus_salivarius             Lansoprazole
38  MetaCardis         Streptococcus_salivarius               Omeprazole
39  MetaCardis          Streptococcus_sanguinis               Olmesartan
40  MetaCardis             Streptococcus_sp_A12              Clopidogrel
41  MetaCardis           Streptococcus_sp_F0442               Irbesartan
42  MetaCardis           Streptococcus_sp_F0442               Omeprazole
43  MetaCardis           Streptococcus_sp_F0442              Rabeprazole
44  MetaCardis      Streptococcus_sp_HMSC070B10               Olmesartan
45  MetaCardis         Streptococcus_sp_HPH0090             Esomeprazole
46  MetaCardis         Streptococcus_sp_HPH0090                Prasugrel
47  MetaCardis            Streptococcus_sp_M334               Olmesartan
48  MetaCardis    Streptococcus_sp_NLAE_zl_C503             Lansoprazole
49  MetaCardis  Streptococcus_sp_oral_taxon_056             Esomeprazole
50  MetaCardis       Streptococcus_vestibularis             Esomeprazole
51  MetaCardis           Streptococcus_viridans             Esomeprazole
52  MetaCardis           Streptococcus_viridans                Prasugrel
53  MetaCardis              Veillonella_atypica               Olmesartan
54  MetaCardis              Veillonella_criceti               Carvedilol
55  MetaCardis         Veillonella_denticariosi            Dapagliflozin
56  MetaCardis               Veillonella_dispar               Irbesartan
57  MetaCardis               Veillonella_dispar              Liraglutide
58  MetaCardis            Veillonella_infantium             Esomeprazole
59  MetaCardis            Veillonella_infantium               Irbesartan
60  MetaCardis            Veillonella_infantium              Liraglutide
61  MetaCardis              Veillonella_parvula               Bisoprolol
62  MetaCardis            Veillonella_seminalis                Metformin
63  MetaCardis            Veillonella_seminalis             Vildagliptin
64  MetaCardis           Veillonella_sp_CAG_933               Gliclazide
65  MetaCardis          Veillonella_sp_T11011_6             Esomeprazole
66  MetaCardis          Veillonella_sp_T11011_6               Olmesartan
67  MetaCardis          Veillonella_sp_T11011_6             Rosuvastatin
68  MetaCardis         Veillonella_tobetsuensis             Esomeprazole

        Cohort                          Species Corresponding Medication
0   MetaCardis              Rothia_mucilaginosa             Esomeprazole
1   MetaCardis              Rothia_mucilaginosa             Lansoprazole
2   MetaCardis              Rothia_mucilaginosa               Omeprazole
3   MetaCardis              Rothia_mucilaginosa              Rabeprazole
4   MetaCardis          Streptococcus_australis               Olmesartan
5   MetaCardis          Streptococcus_cristatus             Rosuvastatin
6   MetaCardis             Streptococcus_downei               Torasemide
7   MetaCardis            Streptococcus_equinus              Clopidogrel
8   MetaCardis            Streptococcus_equinus                Diltiazem
9   MetaCardis            Streptococcus_equinus              Rabeprazole
10  MetaCardis       Streptococcus_gallolyticus              Allopurinol
11  MetaCardis       Streptococcus_gallolyticus                Metformin
12  MetaCardis           Streptococcus_gordonii                 Apixaban
13  MetaCardis           Streptococcus_gordonii             Esomeprazole
14  MetaCardis           Streptococcus_gordonii               Furosemide
15  MetaCardis           Streptococcus_gordonii             Lansoprazole
16  MetaCardis           Streptococcus_gordonii             Vildagliptin
17  MetaCardis           Streptococcus_infantis             Esomeprazole
18  MetaCardis           Streptococcus_infantis               Olmesartan
19  MetaCardis        Streptococcus_macedonicus            Dapagliflozin
20  MetaCardis            Streptococcus_milleri                Metformin
21  MetaCardis            Streptococcus_milleri              Rabeprazole
22  MetaCardis              Streptococcus_mitis             Esomeprazole
23  MetaCardis              Streptococcus_mitis               Furosemide
24  MetaCardis              Streptococcus_mitis               Olmesartan
25  MetaCardis             Streptococcus_oralis              Clopidogrel
26  MetaCardis             Streptococcus_oralis             Esomeprazole
27  MetaCardis             Streptococcus_oralis               Furosemide
28  MetaCardis             Streptococcus_oralis                Metformin
29  MetaCardis             Streptococcus_oralis               Olmesartan
30  MetaCardis             Streptococcus_oralis              Rabeprazole
31  MetaCardis      Streptococcus_parasanguinis              Clopidogrel
32  MetaCardis      Streptococcus_parasanguinis             Esomeprazole
33  MetaCardis      Streptococcus_parasanguinis             Lansoprazole
34  MetaCardis      Streptococcus_parasanguinis                Metformin
35  MetaCardis      Streptococcus_parasanguinis               Omeprazole
36  MetaCardis         Streptococcus_salivarius             Esomeprazole
37  MetaCardis         Streptococcus_salivarius             Lansoprazole
38  MetaCardis         Streptococcus_salivarius               Omeprazole
39  MetaCardis          Streptococcus_sanguinis               Olmesartan
40  MetaCardis             Streptococcus_sp_A12              Clopidogrel
41  MetaCardis           Streptococcus_sp_F0442               Irbesartan
42  MetaCardis           Streptococcus_sp_F0442               Omeprazole
43  MetaCardis           Streptococcus_sp_F0442              Rabeprazole
44  MetaCardis      Streptococcus_sp_HMSC070B10               Olmesartan
45  MetaCardis         Streptococcus_sp_HPH0090             Esomeprazole
46  MetaCardis         Streptococcus_sp_HPH0090                Prasugrel
47  MetaCardis            Streptococcus_sp_M334               Olmesartan
48  MetaCardis    Streptococcus_sp_NLAE_zl_C503             Lansoprazole
49  MetaCardis  Streptococcus_sp_oral_taxon_056             Esomeprazole
50  MetaCardis       Streptococcus_vestibularis             Esomeprazole
51  MetaCardis           Streptococcus_viridans             Esomeprazole
52  MetaCardis           Streptococcus_viridans                Prasugrel
53  MetaCardis              Veillonella_atypica               Olmesartan
54  MetaCardis              Veillonella_criceti               Carvedilol
55  MetaCardis         Veillonella_denticariosi            Dapagliflozin
56  MetaCardis               Veillonella_dispar               Irbesartan
57  MetaCardis               Veillonella_dispar              Liraglutide
58  MetaCardis            Veillonella_infantium             Esomeprazole
59  MetaCardis            Veillonella_infantium               Irbesartan
60  MetaCardis            Veillonella_infantium              Liraglutide
61  MetaCardis              Veillonella_parvula               Bisoprolol
62  MetaCardis            Veillonella_seminalis                Metformin
63  MetaCardis            Veillonella_seminalis             Vildagliptin
64  MetaCardis           Veillonella_sp_CAG_933               Gliclazide
65  MetaCardis          Veillonella_sp_T11011_6             Esomeprazole
66  MetaCardis          Veillonella_sp_T11011_6               Olmesartan
67  MetaCardis          Veillonella_sp_T11011_6             Rosuvastatin
68  MetaCardis         Veillonella_tobetsuensis             Esomeprazole

## Rows Present In XLSX But Not In CSV

In [4]:
display(xlsx_only_rows)
xlsx_only_rows

         Cohort                      Species Corresponding Medication
0   Japanese-4D  Streptococcus_parasanguinis             Esomeprazole
1   Japanese-4D  Streptococcus_parasanguinis             Lansoprazole
2   Japanese-4D  Streptococcus_parasanguinis               Omeprazole
3   Japanese-4D  Streptococcus_parasanguinis              Rabeprazole
4   Japanese-4D     Streptococcus_salivarius             Esomeprazole
5   Japanese-4D     Streptococcus_salivarius             Lansoprazole
6   Japanese-4D     Streptococcus_salivarius               Omeprazole
7   Japanese-4D     Streptococcus_salivarius              Rabeprazole
8   Japanese-4D   Streptococcus_thermophilus             Lansoprazole
9   Japanese-4D   Streptococcus_vestibularis             Esomeprazole
10  Japanese-4D   Streptococcus_vestibularis             Lansoprazole
11  Japanese-4D   Streptococcus_vestibularis               Omeprazole
12  Japanese-4D   Streptococcus_vestibularis              Rabeprazole
13  Japanese-4D          Veillonella_parvula             Esomeprazole
14  Japanese-4D          Veillonella_parvula             Lansoprazole
15   MetaCardis          Rothia_dentocariosa              Rabeprazole
16   MetaCardis     Streptococcus_agalactiae              Fenofibrate
17   MetaCardis     Streptococcus_agalactiae               Torasemide
18   MetaCardis      Streptococcus_anginosus             Esomeprazole
19   MetaCardis      Streptococcus_anginosus               Furosemide
20   MetaCardis      Streptococcus_anginosus             Lansoprazole
21   MetaCardis      Streptococcus_australis              Fluvastatin
22   MetaCardis      Streptococcus_australis             Lansoprazole
23   MetaCardis       Streptococcus_infantis              Fluvastatin
24   MetaCardis       Streptococcus_infantis             Lansoprazole
25   MetaCardis          Streptococcus_mitis              Fluvastatin
26   MetaCardis          Streptococcus_mitis             Lansoprazole
27   MetaCardis          Streptococcus_mitis               Nifedipine
28   MetaCardis         Streptococcus_mutans               Furosemide
29   MetaCardis         Streptococcus_mutans               Olmesartan
30   MetaCardis    Streptococcus_pleomorphus               Indapamide
31   MetaCardis     Streptococcus_salivarius               Irbesartan
32   MetaCardis     Streptococcus_salivarius               Nifedipine
33   MetaCardis       Streptococcus_sobrinus              Fenofibrate
34   MetaCardis   Streptococcus_vestibularis             Lansoprazole
35   MetaCardis   Streptococcus_vestibularis              Pravastatin
36   MetaCardis   Streptococcus_vestibularis                 Warfarin

         Cohort                      Species Corresponding Medication
0   Japanese-4D  Streptococcus_parasanguinis             Esomeprazole
1   Japanese-4D  Streptococcus_parasanguinis             Lansoprazole
2   Japanese-4D  Streptococcus_parasanguinis               Omeprazole
3   Japanese-4D  Streptococcus_parasanguinis              Rabeprazole
4   Japanese-4D     Streptococcus_salivarius             Esomeprazole
5   Japanese-4D     Streptococcus_salivarius             Lansoprazole
6   Japanese-4D     Streptococcus_salivarius               Omeprazole
7   Japanese-4D     Streptococcus_salivarius              Rabeprazole
8   Japanese-4D   Streptococcus_thermophilus             Lansoprazole
9   Japanese-4D   Streptococcus_vestibularis             Esomeprazole
10  Japanese-4D   Streptococcus_vestibularis             Lansoprazole
11  Japanese-4D   Streptococcus_vestibularis               Omeprazole
12  Japanese-4D   Streptococcus_vestibularis              Rabeprazole
13  Japanese-4D          Veillonella_parvula             Esomeprazole
14  Japanese-4D          Veillonella_parvula             Lansoprazole
15   MetaCardis          Rothia_dentocariosa              Rabeprazole
16   MetaCardis     Streptococcus_agalactiae              Fenofibrate
17   MetaCardis     Streptococcus_agalactiae               Torasemide
18   MetaCardis      Streptococcus_anginosus             Esomeprazole
19   MetaCardis      Streptococcus_anginosus               Furosemide
20   MetaCardis      Streptococcus_anginosus             Lansoprazole
21   MetaCardis      Streptococcus_australis              Fluvastatin
22   MetaCardis      Streptococcus_australis             Lansoprazole
23   MetaCardis       Streptococcus_infantis              Fluvastatin
24   MetaCardis       Streptococcus_infantis             Lansoprazole
25   MetaCardis          Streptococcus_mitis              Fluvastatin
26   MetaCardis          Streptococcus_mitis             Lansoprazole
27   MetaCardis          Streptococcus_mitis               Nifedipine
28   MetaCardis         Streptococcus_mutans               Furosemide
29   MetaCardis         Streptococcus_mutans               Olmesartan
30   MetaCardis    Streptococcus_pleomorphus               Indapamide
31   MetaCardis     Streptococcus_salivarius               Irbesartan
32   MetaCardis     Streptococcus_salivarius               Nifedipine
33   MetaCardis       Streptococcus_sobrinus              Fenofibrate
34   MetaCardis   Streptococcus_vestibularis             Lansoprazole
35   MetaCardis   Streptococcus_vestibularis              Pravastatin
36   MetaCardis   Streptococcus_vestibularis                 Warfarin

## Rows Present In CSV But Not In XLSX

In [5]:
display(csv_only_rows)
csv_only_rows

          Cohort                                Species Corresponding Medication
0    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]                 Apixaban
1    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]              Clopidogrel
2    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]             Esomeprazole
3    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]             Lansoprazole
4    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]               Omeprazole
5    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]              Rabeprazole
6    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]              Rivaroxaban
7    Japanese-4D     Streptococcus_salivarius_[ID:0199]             Esomeprazole
8    Japanese-4D     Streptococcus_salivarius_[ID:0199]             Lansoprazole
9    Japanese-4D     Streptococcus_salivarius_[ID:0199]               Omeprazole
10   Japanese-4D     Streptococcus_salivarius_[ID:0199]              Rabeprazole
11   Japanese-4D   Streptococcus_thermophilus_[ID:0219]                 Apixaban
12   Japanese-4D   Streptococcus_thermophilus_[ID:0219]             Lansoprazole
13   Japanese-4D   Streptococcus_vestibularis_[ID:0198]                 Apixaban
14   Japanese-4D   Streptococcus_vestibularis_[ID:0198]             Atorvastatin
15   Japanese-4D   Streptococcus_vestibularis_[ID:0198]              Clopidogrel
16   Japanese-4D   Streptococcus_vestibularis_[ID:0198]                Diltiazem
17   Japanese-4D   Streptococcus_vestibularis_[ID:0198]             Esomeprazole
18   Japanese-4D   Streptococcus_vestibularis_[ID:0198]             Lansoprazole
19   Japanese-4D   Streptococcus_vestibularis_[ID:0198]               Omeprazole
20   Japanese-4D   Streptococcus_vestibularis_[ID:0198]              Rabeprazole
21   Japanese-4D   Streptococcus_vestibularis_[ID:0198]             Vildagliptin
22   Japanese-4D          Veillonella_parvula_[ID:1042]             Esomeprazole
23   Japanese-4D          Veillonella_parvula_[ID:1042]               Furosemide
24   Japanese-4D          Veillonella_parvula_[ID:1042]             Lansoprazole
25   Japanese-4D          Veillonella_parvula_[ID:1042]               Torasemide
26   Japanese-4D        unknown_Streptococcus_[ID:5642]             Esomeprazole
27   Japanese-4D        unknown_Streptococcus_[ID:5642]             Lansoprazole
28   Japanese-4D        unknown_Streptococcus_[ID:5642]               Omeprazole
29   Japanese-4D        unknown_Streptococcus_[ID:5642]              Rabeprazole
30    MetaCardis                    Rothia_dentocariosa                Metformin
31    MetaCardis                    Rothia_mucilaginosa                Metformin
32    MetaCardis                    Rothia_mucilaginosa               Olmesartan
33    MetaCardis                    Rothia_mucilaginosa                Prasugrel
34    MetaCardis                    Rothia_mucilaginosa             Rosuvastatin
35    MetaCardis          Streptococcus_anginosus_group             Esomeprazole
36    MetaCardis          Streptococcus_anginosus_group               Furosemide
37    MetaCardis          Streptococcus_anginosus_group               Omeprazole
38    MetaCardis          Streptococcus_anginosus_group              Rabeprazole
39    MetaCardis                Streptococcus_australis             Atorvastatin
40    MetaCardis                Streptococcus_australis               Irbesartan
41    MetaCardis                Streptococcus_australis              Rabeprazole
42    MetaCardis                Streptococcus_cristatus               Bisoprolol
43    MetaCardis                Streptococcus_cristatus                Metformin
44    MetaCardis                   Streptococcus_downei               Metoprolol
45    MetaCardis                   Streptococcus_downei              Pravastatin
46    MetaCardis                  Streptococcus_equinus             Atorvastatin
47    MetaCardis                 Streptococcus_gordonii              Rabeprazole
48    MetaCardis              Streptococcus_infantarius               Amlodipine
49    MetaCardis                 Streptococcus_infantis              Clopidogrel
50    MetaCardis                 Streptococcus_infantis                Metformin
51    MetaCardis              Streptococcus_lutetiensis                  Aspirin
52    MetaCardis                  Streptococcus_milleri             Lansoprazole
53    MetaCardis                   Streptococcus_mutans               Amiodarone
54    MetaCardis                   Streptococcus_mutans              Clopidogrel
55    MetaCardis                   Streptococcus_mutans                Enalapril
56    MetaCardis                   Streptococcus_mutans                Metformin
57    MetaCardis                   Streptococcus_mutans               Metoprolol
58    MetaCardis                   Streptococcus_oralis             Lansoprazole
59    MetaCardis            Streptococcus_parasanguinis                 Apixaban
60    MetaCardis            Streptococcus_parasanguinis               Olmesartan
61    MetaCardis            Streptococcus_parasanguinis              Rabeprazole
62    MetaCardis             Streptococcus_pasteurianus             Esomeprazole
63    MetaCardis               Streptococcus_salivarius               Olmesartan
64    MetaCardis               Streptococcus_salivarius              Rabeprazole
65    MetaCardis        Streptococcus_salivarius_CAG_79               Irbesartan
66    MetaCardis                Streptococcus_sanguinis              Rabeprazole
67    MetaCardis                 Streptococcus_sobrinus               Amlodipine
68    MetaCardis                 Streptococcus_sobrinus             Esomeprazole
69    MetaCardis                 Streptococcus_sobrinus                Metformin
70    MetaCardis                 Streptococcus_sobrinus             Rosuvastatin
71    MetaCardis                   Streptococcus_sp_A12              Rabeprazole
72    MetaCardis                   Streptococcus_sp_A12             Rosuvastatin
73    MetaCardis                 Streptococcus_sp_F0442             Esomeprazole
74    MetaCardis            Streptococcus_sp_HMSC070B10             Atorvastatin
75    MetaCardis               Streptococcus_sp_HPH0090               Bisoprolol
76    MetaCardis                  Streptococcus_sp_M334             Atorvastatin
77    MetaCardis        Streptococcus_sp_oral_taxon_056             Atorvastatin
78    MetaCardis             Streptococcus_thermophilus               Olmesartan
79    MetaCardis             Streptococcus_vestibularis              Allopurinol
80    MetaCardis             Streptococcus_vestibularis              Clopidogrel
81    MetaCardis                    Veillonella_atypica             Atorvastatin
82    MetaCardis                    Veillonella_atypica             Esomeprazole
83    MetaCardis                    Veillonella_atypica             Rosuvastatin
84    MetaCardis                    Veillonella_criceti               Amlodipine
85    MetaCardis               Veillonella_denticariosi              Sitagliptin
86    MetaCardis                     Veillonella_dispar             Esomeprazole
87    MetaCardis                  Veillonella_infantium               Olmesartan
88    MetaCardis                  Veillonella_infantium              Pravastatin
89    MetaCardis                  Veillonella_infantium             Rosuvastatin
90    MetaCardis                    Veillonella_parvula              Fluvastatin
91    MetaCardis                    Veillonella_parvula               Metoprolol
92    MetaCardis                    Veillonella_parvula               Olmesartan
93    MetaCardis                  Veillonella_rodentium                Prasugrel
94    MetaCardis                    Veillonella_rogosae               Irbesartan
95    MetaCardis                    Veillonella_rogosae               Omeprazole
96    MetaCardis                  Veillonella_seminalis               Indapamide
97    MetaCardis                 Veillonella_sp_CAG_933                Metformin
98    MetaCardis                Veillonella_sp_T11011_6             Atorvastatin
99    MetaCardis                Veillonella_sp_T11011_6               Irbesartan
100   MetaCardis               Veillonella_tobetsuensis               Gliclazide

          Cohort                                Species Corresponding Medication
0    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]                 Apixaban
1    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]              Clopidogrel
2    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]             Esomeprazole
3    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]             Lansoprazole
4    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]               Omeprazole
5    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]              Rabeprazole
6    Japanese-4D  Streptococcus_parasanguinis_[ID:0144]              Rivaroxaban
7    Japanese-4D     Streptococcus_salivarius_[ID:0199]             Esomeprazole
8    Japanese-4D     Streptococcus_salivarius_[ID:0199]             Lansoprazole
9    Japanese-4D     Streptococcus_salivarius_[ID:0199]               Omeprazole
10   Japanese-4D     Streptococcus_salivarius_[ID:0199]              Rabeprazole
11   Japanese-4D   Streptococcus_thermophilus_[ID:0219]                 Apixaban
12   Japanese-4D   Streptococcus_thermophilus_[ID:0219]             Lansoprazole
13   Japanese-4D   Streptococcus_vestibularis_[ID:0198]                 Apixaban
14   Japanese-4D   Streptococcus_vestibularis_[ID:0198]             Atorvastatin
15   Japanese-4D   Streptococcus_vestibularis_[ID:0198]              Clopidogrel
16   Japanese-4D   Streptococcus_vestibularis_[ID:0198]                Diltiazem
17   Japanese-4D   Streptococcus_vestibularis_[ID:0198]             Esomeprazole
18   Japanese-4D   Streptococcus_vestibularis_[ID:0198]             Lansoprazole
19   Japanese-4D   Streptococcus_vestibularis_[ID:0198]               Omeprazole
20   Japanese-4D   Streptococcus_vestibularis_[ID:0198]              Rabeprazole
21   Japanese-4D   Streptococcus_vestibularis_[ID:0198]             Vildagliptin
22   Japanese-4D          Veillonella_parvula_[ID:1042]             Esomeprazole
23   Japanese-4D          Veillonella_parvula_[ID:1042]               Furosemide
24   Japanese-4D          Veillonella_parvula_[ID:1042]             Lansoprazole
25   Japanese-4D          Veillonella_parvula_[ID:1042]               Torasemide
26   Japanese-4D        unknown_Streptococcus_[ID:5642]             Esomeprazole
27   Japanese-4D        unknown_Streptococcus_[ID:5642]             Lansoprazole
28   Japanese-4D        unknown_Streptococcus_[ID:5642]               Omeprazole
29   Japanese-4D        unknown_Streptococcus_[ID:5642]              Rabeprazole
30    MetaCardis                    Rothia_dentocariosa                Metformin
31    MetaCardis                    Rothia_mucilaginosa                Metformin
32    MetaCardis                    Rothia_mucilaginosa               Olmesartan
33    MetaCardis                    Rothia_mucilaginosa                Prasugrel
34    MetaCardis                    Rothia_mucilaginosa             Rosuvastatin
35    MetaCardis          Streptococcus_anginosus_group             Esomeprazole
36    MetaCardis          Streptococcus_anginosus_group               Furosemide
37    MetaCardis          Streptococcus_anginosus_group               Omeprazole
38    MetaCardis          Streptococcus_anginosus_group              Rabeprazole
39    MetaCardis                Streptococcus_australis             Atorvastatin
40    MetaCardis                Streptococcus_australis               Irbesartan
41    MetaCardis                Streptococcus_australis              Rabeprazole
42    MetaCardis                Streptococcus_cristatus               Bisoprolol
43    MetaCardis                Streptococcus_cristatus                Metformin
44    MetaCardis                   Streptococcus_downei               Metoprolol
45    MetaCardis                   Streptococcus_downei              Pravastatin
46    MetaCardis                  Streptococcus_equinus             Atorvastatin
47    MetaCardis                 Streptococcus_gordonii              Rabeprazole
48    MetaCardis              Streptococcus_infantarius               Amlodipine
49    MetaCardis                 Streptococcus_infantis              Clopidogrel
50    MetaCardis                 Streptococcus_infantis                Metformin
51    MetaCardis              Streptococcus_lutetiensis                  Aspirin
52    MetaCardis                  Streptococcus_milleri             Lansoprazole
53    MetaCardis                   Streptococcus_mutans               Amiodarone
54    MetaCardis                   Streptococcus_mutans              Clopidogrel
55    MetaCardis                   Streptococcus_mutans                Enalapril
56    MetaCardis                   Streptococcus_mutans                Metformin
57    MetaCardis                   Streptococcus_mutans               Metoprolol
58    MetaCardis                   Streptococcus_oralis             Lansoprazole
59    MetaCardis            Streptococcus_parasanguinis                 Apixaban
60    MetaCardis            Streptococcus_parasanguinis               Olmesartan
61    MetaCardis            Streptococcus_parasanguinis              Rabeprazole
62    MetaCardis             Streptococcus_pasteurianus             Esomeprazole
63    MetaCardis               Streptococcus_salivarius               Olmesartan
64    MetaCardis               Streptococcus_salivarius              Rabeprazole
65    MetaCardis        Streptococcus_salivarius_CAG_79               Irbesartan
66    MetaCardis                Streptococcus_sanguinis              Rabeprazole
67    MetaCardis                 Streptococcus_sobrinus               Amlodipine
68    MetaCardis                 Streptococcus_sobrinus             Esomeprazole
69    MetaCardis                 Streptococcus_sobrinus                Metformin
70    MetaCardis                 Streptococcus_sobrinus             Rosuvastatin
71    MetaCardis                   Streptococcus_sp_A12              Rabeprazole
72    MetaCardis                   Streptococcus_sp_A12             Rosuvastatin
73    MetaCardis                 Streptococcus_sp_F0442             Esomeprazole
74    MetaCardis            Streptococcus_sp_HMSC070B10             Atorvastatin
75    MetaCardis               Streptococcus_sp_HPH0090               Bisoprolol
76    MetaCardis                  Streptococcus_sp_M334             Atorvastatin
77    MetaCardis        Streptococcus_sp_oral_taxon_056             Atorvastatin
78    MetaCardis             Streptococcus_thermophilus               Olmesartan
79    MetaCardis             Streptococcus_vestibularis              Allopurinol
80    MetaCardis             Streptococcus_vestibularis              Clopidogrel
81    MetaCardis                    Veillonella_atypica             Atorvastatin
82    MetaCardis                    Veillonella_atypica             Esomeprazole
83    MetaCardis                    Veillonella_atypica             Rosuvastatin
84    MetaCardis                    Veillonella_criceti               Amlodipine
85    MetaCardis               Veillonella_denticariosi              Sitagliptin
86    MetaCardis                     Veillonella_dispar             Esomeprazole
87    MetaCardis                  Veillonella_infantium               Olmesartan
88    MetaCardis                  Veillonella_infantium              Pravastatin
89    MetaCardis                  Veillonella_infantium             Rosuvastatin
90    MetaCardis                    Veillonella_parvula              Fluvastatin
91    MetaCardis                    Veillonella_parvula               Metoprolol
92    MetaCardis                    Veillonella_parvula               Olmesartan
93    MetaCardis                  Veillonella_rodentium                Prasugrel
94    MetaCardis                    Veillonella_rogosae               Irbesartan
95    MetaCardis                    Veillonella_rogosae               Omeprazole
96    MetaCardis                  Veillonella_seminalis               Indapamide
97    MetaCardis                 Veillonella_sp_CAG_933                Metformin
98    MetaCardis                Veillonella_sp_T11011_6             Atorvastatin
99    MetaCardis                Veillonella_sp_T11011_6               Irbesartan
100   MetaCardis               Veillonella_tobetsuensis               Gliclazide